### PR TITLE
encode data by hex string

### PR DESCRIPTION
**Pull request by agebhar1**

### CODE REVIEW

**Comment by klingtnet** [comment]
Hi @agebhar1 !

Thank you very much for your contribution!

There are two points that prevent me from merging this change:

1. we do not need to implement hex encoding ourself, `encodeFile` can just use [`EncodeToString` from `encoding/hex`](https://pkg.go.dev/encoding/hex#EncodeToString)
2. The string representation of hex encoded bytes is less efficient than base64 since hex is basically [_base16_](https://en.wikipedia.org/wiki/Hexadecimal) meaning that we have 50% efficiency instead of 67% for base64

**Comment by agebhar1** [comment]
Hi @klingtnet,

thanks for the fast reply.

1. We can't use `EncodeToString` from `encoding/hex` since the result of the function simply returns only the concatenated hexadecimal values of each byte of the string. The output (internal/embeds.go) from running the test is:
```go
const (
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30315f746573742e646f776e2e73716c = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30315f746573742e75702e73716c     = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30335f746573742e75702e73716c     = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30345f746573742e646f776e2e73716c = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30345f746573742e75702e73716c     = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30355f746573742e646f776e2e73716c = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30375f746573742e646f776e2e73716c = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f6d6967726174696f6e732f30375f746573742e75702e73716c     = "2d2d207265717569726564206279206d6967726174652f6472697665725f746573742e676f"
        file696e7465726e616c2f74657374646174612f72616e646f6d2e626c6f62                                 = "dc2418c8a037884e259b8eac0f7ad33d1207c3403defd175ccb9a554a6e821222006cd147765238340e600081b5f8e0f33c86eb0729d26dfdeedd384300f206f3b51d9469bad53b5c83839209aec2e6f6fb379445ec4dd47522cd0756b44bcf9551c89ad5b5065840413b8d106f01c1bd54253da3ba24f8a55fd1c1109d6e121"
        file696e7465726e616c2f74657374646174612f746573742e6a736f6e                                     = "7b226d657373616765223a202248656c6c6f2c20576f726c6421227d0a"
)

```
which is an ordinary string and the test fails. The test fails because the string is used 'as-is'. Each hex represented byte has to be prefixed with `\xXY` to be a byte rather a string `XY` of length 2.

2. The string represented as a sequence of hexadecimal bytes is compiled as byte sequence not as string. A simple comparison of the compiled binary for `internal/embeds.go` with the following `main` function:

```go
func main() {
       for _, f := range Embeds.Files() {
               fmt.Printf("%s => %s\n", f, Embeds.FileString(f))
       }
}
```

*build w/ base64*:
```bash

embed/internal $ go build embeds.go
embed/internal $ ls -ls
insgesamt 2044
2036 -rwxrwxr-x 1 agebhar1 agebhar1 2082193 Nov 15 15:50 embeds
   4 -rw-rw-r-- 1 agebhar1 agebhar1    3983 Nov 15 15:50 embeds.go
   4 drwxrwxr-x 3 agebhar1 agebhar1    4096 Nov 15 13:43 testdata
embed/internal $ ./embeds
internal/testdata/migrations/01_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/01_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/03_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/04_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/04_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/05_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/07_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/07_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/random.blob => $Ƞ7N%z=@=u̹T!" we#S;OU  !
internal/testdata/test.json => {"message": "Hello, World!"}
```

*build w/ hex*:
```bash
embed/internal $ go build embeds.go
embed/internal $ ls -ls
insgesamt 2044
2024 -rwxrwxr-x 1 agebhar1 agebhar1 2068845 Nov 15 15:52 embeds
   8 -rw-rw-r-- 1 agebhar1 agebhar1    5093 Nov 15 15:52 embeds.go
   4 drwxrwxr-x 3 agebhar1 agebhar1    4096 Nov 15 13:43 testdata
embed/internal $ ./embeds
internal/testdata/migrations/01_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/01_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/03_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/04_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/04_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/05_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/07_test.down.sql => -- required by migrate/driver_test.go
internal/testdata/migrations/07_test.up.sql => -- required by migrate/driver_test.go
internal/testdata/random.blob => $Ƞ7N%z=@=u̹T!" we#S;OU  !
internal/testdata/test.json => {"message": "Hello, World!"}
```

so the overhead to embed files should be zero (maybe some compiler padding).

**Comment by klingtnet** [comment]
Thank you for the reply.

1. You're correct and with this approach we can read the data without decoding first by just casting the string.  Nonetheless, I am unsure if the performance benefit will outweigh the cost of larger `embeds.go` (see 2.) and maintaining the self-rolled encoder.  Performance should not be an issue, although I did not measure the duration it takes to base64 decode the strings (I guess it's neglible).

2. The `embeds.go` generated by using hex encoding is still about 25% percent larger than the one using base64 encoding:

```sh
$ git checkout -q master && stat --format %s internal/embeds.go
3871
$ git checkout -q feature/hex && stat --format %s internal/embeds.go
4980
```

**Comment by agebhar1** [comment]
Hi @klingtnet,

1. I've no idea if the decoding is negligible or not. Maybe a benchmark give us details ;)
2. The `embeds.go` is larger, but it's the source only and not the compiled binary. I guess `git` would compress the files if it is one of your concerns.

**Comment by agebhar1** [comment]
Hi @klingtnet,

instead of encode each byte as hexadecimal the latest commit utilize `Sprintf` [string format option](https://blog.golang.org/strings) `%q` (quoted). The size of the binary equals but the size of the source file is (much) smaller in case of UTF-8 embed files.

**Comment by klingtnet** [comment]
That's pretty clever.  Let me have a look this evening.

**Comment by klingtnet** [comment]
I rebased this branch against the `benchmark` branch to get some performance numbers.  Note that I did not run a decoding test since I this would required to prepare a embeds.go file before each benchmark run, doable but cumbersome.  Also, we now that decoding cost for this solution is zero and for `base64` almost zero.

Following are the results for `hex` encoding using `Sprintf`:

```sh
$ go test -v -run=Benchmark -bench=. ./...
?       github.com/klingtnet/embed      [no test files]
goos: linux
goarch: amd64
pkg: github.com/klingtnet/embed/cmd/embed
BenchmarkEncoding
BenchmarkEncoding/100k
BenchmarkEncoding/100k-16               1000000000               0.00373 ns/op         0 B/op          0 allocs/op
BenchmarkEncoding/1MiB
BenchmarkEncoding/1MiB-16               1000000000               0.0509 ns/op          0 B/op          0 allocs/op
BenchmarkEncoding/10MiB
BenchmarkEncoding/10MiB-16              1000000000               0.424 ns/op           0 B/op          0 allocs/op
BenchmarkEncoding/100MiB
BenchmarkEncoding/100MiB-16                    1        2909030721 ns/op        4764616840 B/op       14 allocs/op
BenchmarkEncoding/1GiB
BenchmarkEncoding/1GiB-16                      1        32330782524 ns/op       48787531912 B/op              14 allocs/op
BenchmarkEmbed
BenchmarkEmbed/100k
BenchmarkEmbed/100k-16                         1        9905836066 ns/op        7222214264 B/op   113907 allocs/op
BenchmarkEmbed/1MiB
BenchmarkEmbed/1MiB-16                         1        6505702729 ns/op        7703014752 B/op    12459 allocs/op
BenchmarkEmbed/10MiB
BenchmarkEmbed/10MiB-16                        1        6395423724 ns/op        7292683840 B/op     1949 allocs/op
BenchmarkEmbed/100MiB
BenchmarkEmbed/100MiB-16                       1        5700652117 ns/op        5436572312 B/op      828 allocs/op
PASS
ok      github.com/klingtnet/embed/cmd/embed    73.895s
?       github.com/klingtnet/embed/internal     [no test files]
PASS
ok      github.com/klingtnet/embed/migrate      0.006s
```

the numbers for `base64` are:

```sh
$ go test -v -run=Benchmark -bench=. ./...
?   	github.com/klingtnet/embed	[no test files]
goos: linux
goarch: amd64
pkg: github.com/klingtnet/embed/cmd/embed
BenchmarkEncoding
BenchmarkEncoding/100k
BenchmarkEncoding/100k-16         	1000000000	         0.000302 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncoding/1MiB
BenchmarkEncoding/1MiB-16         	1000000000	         0.00325 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncoding/10MiB
BenchmarkEncoding/10MiB-16        	1000000000	         0.0314 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncoding/100MiB
BenchmarkEncoding/100MiB-16       	1000000000	         0.212 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncoding/1GiB
BenchmarkEncoding/1GiB-16         	       1	2051404069 ns/op	5726633984 B/op	       2 allocs/op
BenchmarkEmbed
BenchmarkEmbed/100k
BenchmarkEmbed/100k-16            	       1	2167880930 ns/op	3111582256 B/op	  104959 allocs/op
BenchmarkEmbed/1MiB
BenchmarkEmbed/1MiB-16            	       1	2067493575 ns/op	3441635264 B/op	   11616 allocs/op
BenchmarkEmbed/10MiB
BenchmarkEmbed/10MiB-16           	       1	1931334318 ns/op	3178146736 B/op	    1927 allocs/op
BenchmarkEmbed/100MiB
BenchmarkEmbed/100MiB-16          	       1	1636743340 ns/op	2225861272 B/op	     889 allocs/op
PASS
ok  	github.com/klingtnet/embed/cmd/embed	14.454s
?   	github.com/klingtnet/embed/internal	[no test files]
PASS
ok  	github.com/klingtnet/embed/migrate	0.003s
```

More details can be found in commit c0b5183e754dead581728ceca8737d0d4a7a0753 .

**Comment by klingtnet** [comment]
I am sorry for closing this, but I will keep `base64` as for now.  The reasons are as follows:

- single line implementation
- no memory overhead (see `allocs/op` for `BenchmarkEncoding`)
- 25% smaller embedded file size
- decoding base64 encoded content from memory is fast enough (faster than disk I/O for sure).

Still, many thanks for the implementation!  If a requirement for zero cost decoding comes up then we can still reuse this.

**Comment by agebhar1** [comment]
No worries.

Thank you for your time @klingtnet and the benchmark.

I didn't expect that encode Base64 is faster than `Sprintf` with `%q`. I tested with the pure hex encoding, the benchmark is better as with quoted encoding but not as good as with Base64. The Go implementation of Base64 is pretty fast.

With binary data the quoted encoding is almost equal to the hex encoding and and yields to larger source files, that leads to increased compile time and memory. On the other hand, text data, like embedded JavaScript or CSS the quoted encoding produces no overhead in comparison to Base64.

So, feel free to use the code whenever there is a need. A mixed mode or compile time decisions based on the type of data to embed came to my mind ...

**Pull request closed without merging**
